{
  "hash": "c618e24adfd68a1f1788ea8bfa720bbb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"EdNet-KT1 探索的データ分析\"\nsubtitle: \"55万インタラクションから読み解く TOEIC学習者の行動パターン\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"コードを表示\"\n    theme: cosmo\n    fig-width: 10\n    fig-height: 5.5\njupyter: python3\nexecute:\n  cache: true\n  warning: false\n---\n\n## はじめに — このノートブックの目的\n\n**EdNet-KT1** は、韓国の AI 教育企業 Riiid が公開した世界最大級の学習行動ログデータセットである。TOEIC 対策アプリ *Santa* の実ユーザーから収集された約 78 万人・1.3 億行のインタラクションを含む。\n\n本ノートブックでは、そのうち **5,000 ユーザー・約 55 万行** のサンプルを対象に、以下の問いに答える:\n\n1. **誰が学んでいるのか** — ユーザーのエンゲージメント構造と二極化\n2. **何を解いているのか** — TOEIC Part 別・スキルタグ別の出題と正答率\n3. **どう解いているのか** — 解答時間の分布と異常値\n4. **学習は進んでいるのか** — 系列内の正答率推移（学習曲線）\n\n最終的に、Knowledge Tracing (KT) モデルの学習に向けた前処理方針を導出する。\n\n::: {.callout-note}\n実行前に `make download` で `data/raw/KT1/` と `questions.csv` を配置しておくこと。\n:::\n\n## 1. セットアップ\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\nfrom pathlib import Path\nimport polars as pl\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib.ticker as ticker\n\n# --- Project paths ---\nPROJECT_ROOT = next(\n    p for p in [Path.cwd(), *Path.cwd().parents] if (p / \"pyproject.toml\").exists()\n)\nRAW_DIR = PROJECT_ROOT / \"data\" / \"raw\"\nPROCESSED_DIR = PROJECT_ROOT / \"data\" / \"processed\"\nN_USERS = 5_000\nSEED = 42\n\n# --- Japanese font ---\nimport matplotlib.font_manager as fm\n\njp_fonts = [\n    f.name for f in fm.fontManager.ttflist\n    if \"Hiragino\" in f.name or \"Gothic\" in f.name or \"Noto Sans CJK\" in f.name\n]\nif jp_fonts:\n    plt.rcParams[\"font.family\"] = jp_fonts[0]\nplt.rcParams[\"axes.unicode_minus\"] = False\n\n# --- Palette ---\nBLUE = \"#4C72B0\"\nORANGE = \"#DD8452\"\nGREEN = \"#55A868\"\nRED = \"#C44E52\"\n```\n:::\n\n\n::: {#load-data .cell execution_count=2}\n``` {.python .cell-code}\nfrom src.data.sample import build_sample\n\nresult = build_sample(RAW_DIR, n_users=N_USERS, seed=SEED, processed_dir=PROCESSED_DIR)\ndf = result.df\nseq_lens = df.group_by(\"user_id\").agg(pl.len().alias(\"n\"))\n```\n:::\n\n\n## 2. データの全体像\n\nこのサンプルの規模感を把握する。\n\n::: {#tbl-overview .cell execution_count=3}\n``` {.python .cell-code}\nsummary = {\n    \"ユーザー数\": f\"{result.n_users:,}\",\n    \"総インタラクション数\": f\"{result.n_rows:,}\",\n    \"ユニーク問題数\": f\"{df['question_id'].n_unique():,}\",\n    \"ユニークバンドル数\": f\"{df['bundle_id'].n_unique():,}\",\n    \"ユニークスキルタグ数\": f\"{df.explode('tags').filter(pl.col('tags').is_not_null())['tags'].n_unique():,}\",\n    \"データ期間\": f\"{__import__('datetime').datetime.fromtimestamp(df['timestamp'].min()/1000).strftime('%Y-%m-%d')} 〜 {__import__('datetime').datetime.fromtimestamp(df['timestamp'].max()/1000).strftime('%Y-%m-%d')}\",\n    \"全体正答率\": f\"{df.filter(pl.col('correct').is_not_null())['correct'].mean():.1%}\",\n    \"correct 欠損行\": f\"{df.filter(pl.col('correct').is_null()).height:,}\",\n}\npl.DataFrame({\"指標\": list(summary.keys()), \"値\": list(summary.values())})\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (8, 2)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>指標</th><th>値</th></tr><tr><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;ユーザー数&quot;</td><td>&quot;5,000&quot;</td></tr><tr><td>&quot;総インタラクション数&quot;</td><td>&quot;555,315&quot;</td></tr><tr><td>&quot;ユニーク問題数&quot;</td><td>&quot;11,942&quot;</td></tr><tr><td>&quot;ユニークバンドル数&quot;</td><td>&quot;8,720&quot;</td></tr><tr><td>&quot;ユニークスキルタグ数&quot;</td><td>&quot;188&quot;</td></tr><tr><td>&quot;データ期間&quot;</td><td>&quot;2017-05-02 〜 2019-12-03&quot;</td></tr><tr><td>&quot;全体正答率&quot;</td><td>&quot;65.1%&quot;</td></tr><tr><td>&quot;correct 欠損行&quot;</td><td>&quot;108&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n5,000 ユーザーで **約 55 万行**、問題プールは **11,942 問** × **188 スキルタグ**。\nデータは **2017-05 〜 2019-12** の約 2.5 年間をカバーする。\n全体正答率は **65.1%** と一見高いが、これはヘビーユーザー（正答率が高い）の行数が大きいためであり、ユーザー単位で見ると様相が異なる。次節でこの構造を明らかにする。\n\n## 3. 誰が学んでいるのか — ユーザーエンゲージメントの二極化\n\n### 3.1 系列長の分布\n\n::: {#cell-fig-seq-len .cell execution_count=4}\n``` {.python .cell-code}\nn_arr = seq_lens[\"n\"].to_numpy()\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\n\n# Left: log-scale histogram\nax = axes[0]\nax.hist(n_arr, bins=np.logspace(0, np.log10(n_arr.max()), 50),\n        color=BLUE, edgecolor=\"white\", linewidth=0.3)\nax.set_xscale(\"log\")\nax.set_xlabel(\"系列長（問題数, log スケール）\")\nax.set_ylabel(\"ユーザー数\")\nax.set_title(\"系列長ヒストグラム\", fontweight=\"bold\")\nax.axvline(np.median(n_arr), color=\"tomato\", ls=\"--\", lw=1.5,\n           label=f\"中央値 = {int(np.median(n_arr))}\")\nax.legend(fontsize=9)\n\n# Right: ECDF\nax2 = axes[1]\nsorted_n = np.sort(n_arr)\necdf = np.arange(1, len(sorted_n) + 1) / len(sorted_n)\nax2.plot(sorted_n, ecdf, color=BLUE, lw=1.5)\nax2.set_xscale(\"log\")\nax2.set_xlabel(\"系列長（問題数, log スケール）\")\nax2.set_ylabel(\"累積割合\")\nax2.set_title(\"累積分布関数 (ECDF)\", fontweight=\"bold\")\nfor q, lbl in [(10, \"10以下\"), (100, \"100以下\"), (500, \"500以下\")]:\n    frac = np.mean(n_arr <= q)\n    ax2.axhline(frac, color=\"gray\", ls=\":\", lw=0.8, alpha=0.5)\n    ax2.annotate(f\"{lbl}: {frac:.0%}\", xy=(q, frac),\n                 fontsize=8, color=\"gray\", ha=\"right\")\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図1: ユーザーごとの解答系列長 — ヒストグラムと累積分布](01-eda_files/figure-html/fig-seq-len-output-1.png){#fig-seq-len width=1237 height=467}\n:::\n:::\n\n\n系列長の分布は典型的な **冪則 (power-law)** を示す。中央値はわずか **11 問** — つまり半数のユーザーは 10 問程度で離脱している。一方、上位数パーセントのヘビーユーザーは数千問を解いている。\n\n### 3.2 エンゲージメントセグメント\n\nユーザーを解答数で4段階に分類し、各セグメントがデータに占める比重を可視化する。\n\n::: {#cell-fig-segments .cell execution_count=5}\n``` {.python .cell-code}\nsegments = [\n    (\"Casual\\n(10問以下)\", 0, 10),\n    (\"Moderate\\n(11-100問)\", 10, 100),\n    (\"Active\\n(101-500問)\", 100, 500),\n    (\"Power\\n(500問超)\", 500, 100_000),\n]\n\nseg_data = []\nfor label, lo, hi in segments:\n    uids = seq_lens.filter((pl.col(\"n\") > lo) & (pl.col(\"n\") <= hi))\n    n_users = uids.height\n    n_rows = df.join(uids.select(\"user_id\"), on=\"user_id\").height\n    seg_df = df.join(uids.select(\"user_id\"), on=\"user_id\").filter(pl.col(\"correct\").is_not_null())\n    acc = float(seg_df[\"correct\"].mean()) if seg_df.height > 0 else 0\n    seg_data.append((label, n_users, n_rows, acc))\n\nlabels_seg = [s[0] for s in seg_data]\nusers_pct = [s[1] / N_USERS for s in seg_data]\nrows_pct = [s[2] / result.n_rows for s in seg_data]\naccs_seg = [s[3] for s in seg_data]\ncolors_seg = [RED, ORANGE, GREEN, BLUE]\n\nfig, axes = plt.subplots(1, 3, figsize=(15, 5))\n\n# Users pie\naxes[0].pie(users_pct, labels=labels_seg, colors=colors_seg,\n            autopct=\"%1.0f%%\", startangle=90, textprops={\"fontsize\": 9})\naxes[0].set_title(\"ユーザー構成比\", fontweight=\"bold\")\n\n# Rows pie\naxes[1].pie(rows_pct, labels=labels_seg, colors=colors_seg,\n            autopct=\"%1.0f%%\", startangle=90, textprops={\"fontsize\": 9})\naxes[1].set_title(\"データ行数構成比\", fontweight=\"bold\")\n\n# Accuracy bars\nbars = axes[2].barh(labels_seg, accs_seg, color=colors_seg, height=0.6)\naxes[2].set_xlim(0, 1)\naxes[2].xaxis.set_major_formatter(ticker.PercentFormatter(1.0))\naxes[2].set_title(\"セグメント別正答率\", fontweight=\"bold\")\nfor bar, a in zip(bars, accs_seg):\n    axes[2].text(a + 0.02, bar.get_y() + bar.get_height() / 2,\n                 f\"{a:.1%}\", va=\"center\", fontsize=9)\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図2: エンゲージメントセグメント — ユーザー構成比 vs データ構成比](01-eda_files/figure-html/fig-segments-output-1.png){#fig-segments width=1428 height=469}\n:::\n:::\n\n\nここに**データの核心的な不均衡**がある:\n\n- **Casual ユーザー (≤10問)** はユーザーの **48%** を占めるが、データ行数ではわずか **2.5%**\n- **Power ユーザー (500問超)** はユーザーの **5%** に過ぎないが、データの **67%** を生成\n- 正答率も Casual **44.8%** → Power **68.4%** と **23.6pp** の開きがある\n\nKT モデルはこの Power ユーザーの長い系列から主に学習することになる。Casual ユーザーの短い系列では正答率予測の精度が低くなりやすく、cold-start 問題に直結する。\n\n### 3.3 ユーザー別正答率の分布\n\n::: {#cell-fig-user-acc .cell execution_count=6}\n``` {.python .cell-code}\nuser_acc = (\n    df.filter(pl.col(\"correct\").is_not_null())\n    .group_by(\"user_id\")\n    .agg(pl.col(\"correct\").mean().alias(\"user_acc\"))\n)\nua = user_acc[\"user_acc\"].to_numpy()\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\nax.hist(ua, bins=50, color=BLUE, edgecolor=\"white\", linewidth=0.4, density=True)\nax.axvline(np.median(ua), color=\"tomato\", ls=\"--\", lw=1.5,\n           label=f\"中央値 = {np.median(ua):.0%}\")\nax.axvline(np.mean(ua), color=ORANGE, ls=\":\", lw=1.5,\n           label=f\"平均 = {np.mean(ua):.0%}\")\nax.set_xlabel(\"ユーザー別正答率\")\nax.set_ylabel(\"密度\")\nax.set_title(\"ユーザー別正答率の分布\", fontsize=13, fontweight=\"bold\")\nax.xaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.legend(fontsize=9)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図3: ユーザー別正答率の分布](01-eda_files/figure-html/fig-user-acc-output-1.png){#fig-user-acc width=854 height=421}\n:::\n:::\n\n\nユーザー単位の平均正答率は**中央値 50%、平均 49%** と、全体の 65% よりも大幅に低い。\n分布は 0% 付近と 100% 付近に集中する**U字型**で、「ほとんど正解できないユーザー」と「ほぼ全問正解するユーザー」が共存している。これは Casual ユーザー（数問しか解かず偏った結果になる）の影響が大きい。\n\n## 4. 何を解いているのか — 問題とスキルの構造\n\n### 4.1 問題ごとの出題頻度と正答率\n\n::: {#cell-fig-question-scatter .cell execution_count=7}\n``` {.python .cell-code}\nq_stats = (\n    df.group_by(\"question_id\")\n    .agg(\n        pl.len().alias(\"n_attempts\"),\n        pl.col(\"correct\").mean().alias(\"acc\"),\n    )\n    .sort(\"n_attempts\", descending=True)\n)\nn_att = q_stats[\"n_attempts\"].to_numpy()\nacc_q = q_stats[\"acc\"].to_numpy()\n\nfig, ax = plt.subplots(figsize=(9, 5.5))\nsc = ax.scatter(n_att, acc_q, c=np.log10(n_att), cmap=\"viridis\",\n                s=6, alpha=0.5, edgecolors=\"none\")\nax.set_xscale(\"log\")\nax.set_xlabel(\"出題回数 (log)\")\nax.set_ylabel(\"正答率\")\nax.yaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.set_title(\"問題ごとの出題頻度と正答率\", fontsize=13, fontweight=\"bold\")\ncbar = fig.colorbar(sc, ax=ax, label=\"log₁₀(出題回数)\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図4: 問題ごとの出題回数 vs 正答率（色 = 出題回数の対数）](01-eda_files/figure-html/fig-question-scatter-output-1.png){#fig-question-scatter width=810 height=516}\n:::\n:::\n\n\n**11,942 問**の正答率は 0% 〜 100% まで広く分布し、アイテムプールの難易度多様性は高い。出題回数が少ない問題ほど正答率の分散が大きい（サンプルサイズ効果）。高頻度問題は正答率 50-80% 帯に集中しており、アダプティブ出題の効果が示唆される。\n\n### 4.2 TOEIC Part 別の出題量と正答率\n\n::: {#cell-fig-part .cell execution_count=8}\n``` {.python .cell-code}\npart_stats = (\n    df.group_by(\"part\")\n    .agg(\n        pl.len().alias(\"n\"),\n        pl.col(\"correct\").mean().alias(\"acc\"),\n        pl.col(\"elapsed_time\").median().alias(\"median_time_ms\"),\n    )\n    .sort(\"part\")\n)\n\npart_labels = {\n    1: \"P1 写真描写\", 2: \"P2 応答\", 3: \"P3 会話\",\n    4: \"P4 説明文\", 5: \"P5 短文穴埋め\",\n    6: \"P6 長文穴埋め\", 7: \"P7 読解\",\n}\nparts = part_stats[\"part\"].to_numpy()\ncounts = part_stats[\"n\"].to_numpy()\naccs_p = part_stats[\"acc\"].to_numpy()\nlabels_p = [part_labels.get(int(p), f\"P{p}\") for p in parts]\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n\n# Left: bar chart of counts\ncolors_p = plt.cm.Set2(np.linspace(0, 1, 7))\nax1.barh(labels_p[::-1], counts[::-1], color=colors_p[::-1], height=0.6)\nax1.set_xlabel(\"出題数\")\nax1.set_title(\"Part 別出題数\", fontweight=\"bold\")\nfor i, (c, l) in enumerate(zip(counts[::-1], labels_p[::-1])):\n    ax1.text(c + 1000, i, f\"{c:,}\", va=\"center\", fontsize=8)\n\n# Right: accuracy with median elapsed time\nax2.barh(labels_p[::-1], accs_p[::-1], color=colors_p[::-1], height=0.6)\nax2.set_xlim(0, 1)\nax2.xaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax2.set_title(\"Part 別正答率\", fontweight=\"bold\")\nfor i, a in enumerate(accs_p[::-1]):\n    ax2.text(a + 0.01, i, f\"{a:.1%}\", va=\"center\", fontsize=8)\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図5: TOEIC Part 別の出題数と正答率](01-eda_files/figure-html/fig-part-output-1.png){#fig-part width=1334 height=468}\n:::\n:::\n\n\n| パターン | 詳細 |\n|---|---|\n| **出題量** | Part 5 (短文穴埋め) が **23 万行**で圧倒的に多い。1問完結で出題しやすいためと考えられる |\n| **正答率** | リスニング (P1-P4) が **63-75%** と高く、リーディング (P5-P7) が **59-68%** と低い |\n| **最難関** | Part 5 の正答率 **59.5%** が最も低く、語彙・文法の弱点を反映 |\n\n### 4.3 スキルタグ別の正答率\n\n::: {#cell-fig-tags .cell execution_count=9}\n``` {.python .cell-code}\ntag_stats = (\n    df.explode(\"tags\")\n    .group_by(\"tags\")\n    .agg(\n        pl.len().alias(\"n\"),\n        pl.col(\"correct\").mean().alias(\"acc\"),\n    )\n    .sort(\"n\", descending=True)\n)\ntop20 = tag_stats.head(20).sort(\"acc\")\n\ntags_arr = top20[\"tags\"].cast(pl.Utf8).to_numpy()\nacc_arr = top20[\"acc\"].to_numpy()\nn_tags = top20[\"n\"].to_numpy()\n\nfig, ax = plt.subplots(figsize=(9, 6))\ncolors_t = plt.cm.YlOrRd(n_tags / n_tags.max())\nbars = ax.barh(tags_arr, acc_arr, color=colors_t, height=0.7)\nax.set_xlim(0, 1)\nax.xaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.set_xlabel(\"正答率\")\nax.set_title(\"上位20スキルタグの正答率\", fontsize=13, fontweight=\"bold\")\n\n# Colorbar for count\nimport matplotlib.cm as cm\nsm = cm.ScalarMappable(cmap=\"YlOrRd\",\n                       norm=plt.Normalize(vmin=n_tags.min(), vmax=n_tags.max()))\nsm.set_array([])\nfig.colorbar(sm, ax=ax, label=\"出題数\", shrink=0.8)\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図6: 上位20スキルタグの正答率（出題数による色分け）](01-eda_files/figure-html/fig-tags-output-1.png){#fig-tags width=836 height=565}\n:::\n:::\n\n\n**188 種のスキルタグ** は TOEIC の個別スキル（語彙、文法項目、リスニング戦略等）に対応する。タグ間の正答率差は最大で **30pp 以上**あり、KT モデルが concept-level で知識状態を推定するための情報源として有効である。1問あたり平均 **2.4 タグ**が付与されており、multi-skill 構造を持つ。\n\n## 5. どう解いているのか — 解答時間の分析\n\n### 5.1 解答時間の全体分布と Part 別比較\n\n::: {#cell-fig-elapsed .cell execution_count=10}\n``` {.python .cell-code}\nelapsed_sec = df.with_columns(\n    (pl.col(\"elapsed_time\") / 1000).alias(\"elapsed_sec\")\n)\n\nfig, axes = plt.subplots(1, 2, figsize=(13, 5))\n\n# Left: overall histogram (capped at 120sec)\nax = axes[0]\ne = elapsed_sec.filter(pl.col(\"elapsed_sec\") <= 120)[\"elapsed_sec\"].to_numpy()\nax.hist(e, bins=60, color=BLUE, edgecolor=\"white\", linewidth=0.3, density=True)\nax.axvline(np.median(e), color=\"tomato\", ls=\"--\", lw=1.5,\n           label=f\"中央値 = {np.median(e):.0f}秒\")\nax.set_xlabel(\"解答時間 (秒)\")\nax.set_ylabel(\"密度\")\nax.set_title(\"解答時間の分布（120秒以下）\", fontweight=\"bold\")\nax.legend(fontsize=9)\n\n# Right: Part-wise boxplot\nax = axes[1]\nbox_data = []\npart_labels_short = []\nfor p in range(1, 8):\n    vals = elapsed_sec.filter(\n        (pl.col(\"part\") == p) & (pl.col(\"elapsed_sec\") <= 120)\n    )[\"elapsed_sec\"].to_numpy()\n    box_data.append(vals)\n    part_labels_short.append(f\"P{p}\")\n\nbp = ax.boxplot(box_data, tick_labels=part_labels_short, patch_artist=True,\n                showfliers=False, medianprops={\"color\": \"black\", \"lw\": 1.5})\nfor patch, c in zip(bp[\"boxes\"], plt.cm.Set2(np.linspace(0, 1, 7))):\n    patch.set_facecolor(c)\nax.set_ylabel(\"解答時間 (秒)\")\nax.set_title(\"Part 別解答時間\", fontweight=\"bold\")\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図7: 解答時間の分布 — 全体ヒストグラム (左) と Part 別箱ひげ図 (右)](01-eda_files/figure-html/fig-elapsed-output-1.png){#fig-elapsed width=1238 height=469}\n:::\n:::\n\n\n解答時間の中央値は約 **22 秒**。Part 4 (説明文リスニング) と Part 7 (長文読解) は中央値が 40-50 秒超と長い一方、Part 1 (写真描写) や Part 5 (短文穴埋め) は 15-20 秒で速い。\n\n### 5.2 解答時間の外れ値\n\n::: {#tbl-outlier .cell execution_count=11}\n``` {.python .cell-code}\ntotal = len(df)\noutlier_data = {\n    \"条件\": [\"0 ms（未回答/バグ）\", \"< 1秒（推測回答）\", \"> 60秒\", \"> 5分\"],\n    \"件数\": [\n        f\"{df.filter(pl.col('elapsed_time') == 0).height:,}\",\n        f\"{df.filter(pl.col('elapsed_time') < 1000).height:,}\",\n        f\"{df.filter(pl.col('elapsed_time') > 60_000).height:,}\",\n        f\"{df.filter(pl.col('elapsed_time') > 300_000).height:,}\",\n    ],\n    \"割合\": [\n        f\"{df.filter(pl.col('elapsed_time') == 0).height / total:.2%}\",\n        f\"{df.filter(pl.col('elapsed_time') < 1000).height / total:.2%}\",\n        f\"{df.filter(pl.col('elapsed_time') > 60_000).height / total:.2%}\",\n        f\"{df.filter(pl.col('elapsed_time') > 300_000).height / total:.2%}\",\n    ],\n}\npl.DataFrame(outlier_data)\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div><style>\n.dataframe > thead > tr,\n.dataframe > tbody > tr {\n  text-align: right;\n  white-space: pre-wrap;\n}\n</style>\n<small>shape: (4, 3)</small><table border=\"1\" class=\"dataframe\"><thead><tr><th>条件</th><th>件数</th><th>割合</th></tr><tr><td>str</td><td>str</td><td>str</td></tr></thead><tbody><tr><td>&quot;0 ms（未回答/バグ）&quot;</td><td>&quot;1,665&quot;</td><td>&quot;0.30%&quot;</td></tr><tr><td>&quot;&lt; 1秒（推測回答）&quot;</td><td>&quot;2,882&quot;</td><td>&quot;0.52%&quot;</td></tr><tr><td>&quot;&gt; 60秒&quot;</td><td>&quot;28,641&quot;</td><td>&quot;5.16%&quot;</td></tr><tr><td>&quot;&gt; 5分&quot;</td><td>&quot;402&quot;</td><td>&quot;0.07%&quot;</td></tr></tbody></table></div>\n```\n:::\n:::\n\n\n- **0 ms** の行が 0.3% (1,665件) 存在 — アプリの不具合か未回答\n- **1秒未満**は 0.5% — 問題を読まずに推測した可能性が高い\n- **5分超**は 0.07% — 離席・中断と推測\n\n→ KT モデル学習時は `elapsed_time < 1000 ms` と `> 300,000 ms` を除外またはクリッピングする方針を推奨。\n\n### 5.3 解答時間と正答の関係\n\n::: {#cell-fig-elapsed-correct .cell execution_count=12}\n``` {.python .cell-code}\ncorr_data = df.filter(\n    pl.col(\"correct\").is_not_null()\n    & (pl.col(\"elapsed_time\") > 0)\n    & (pl.col(\"elapsed_time\") <= 120_000)\n)\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\nfor val, label, color in [(1, \"正解\", GREEN), (0, \"不正解\", RED)]:\n    subset = corr_data.filter(pl.col(\"correct\") == val)[\"elapsed_time\"].to_numpy() / 1000\n    ax.hist(subset, bins=60, alpha=0.5, color=color, label=label,\n            density=True, edgecolor=\"white\", linewidth=0.3)\nax.set_xlabel(\"解答時間 (秒)\")\nax.set_ylabel(\"密度\")\nax.set_title(\"正解/不正解別の解答時間分布\", fontsize=13, fontweight=\"bold\")\nax.legend(fontsize=10)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図8: 正解/不正解別の解答時間分布](01-eda_files/figure-html/fig-elapsed-correct-output-1.png){#fig-elapsed-correct width=854 height=421}\n:::\n:::\n\n\n解答時間と正誤のピアソン相関は **r = −0.059** とほぼ無相関だが、分布を重ねると**正解群の方がやや短時間寄り**であることがわかる。これは「知っている問題は素早く解ける」という直感と整合する。ただし、この特徴量だけで正誤を予測する力は弱い。\n\n## 6. 学習は進んでいるのか — 系列内の正答率推移\n\n::: {#cell-fig-learning-curve .cell execution_count=13}\n``` {.python .cell-code}\nrank_acc = (\n    df.filter(pl.col(\"correct\").is_not_null())\n    .with_columns(\n        (pl.col(\"solving_id\").rank(\"ordinal\").over(\"user_id\") // 10 * 10)\n        .cast(pl.Int32)\n        .alias(\"rank_bin\")\n    )\n    .group_by(\"rank_bin\")\n    .agg(\n        pl.col(\"correct\").mean().alias(\"acc\"),\n        pl.len().alias(\"n\"),\n    )\n    .sort(\"rank_bin\")\n    .filter(pl.col(\"n\") >= 50)  # 十分なサンプルサイズの bin のみ\n)\n\nrb = rank_acc[\"rank_bin\"].to_numpy()\nra = rank_acc[\"acc\"].to_numpy()\nrn = rank_acc[\"n\"].to_numpy()\n\nfig, ax = plt.subplots(figsize=(10, 5))\n\n# Scatter with size = sample count\nax.scatter(rb, ra, s=np.clip(rn / 20, 5, 80), color=BLUE, alpha=0.4, edgecolors=\"none\")\n\n# Moving average\nwindow = 5\nif len(ra) > window:\n    ma = np.convolve(ra, np.ones(window) / window, mode=\"valid\")\n    ax.plot(rb[window // 2: window // 2 + len(ma)], ma,\n            color=ORANGE, lw=2.5, label=f\"移動平均 (w={window})\")\n\nax.set_xlabel(\"ユーザー内の解答順位 (10問単位ビン)\")\nax.set_ylabel(\"正答率\")\nax.yaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.set_title(\"学習曲線: 解答順序と正答率の推移\", fontsize=13, fontweight=\"bold\")\nax.legend(fontsize=10)\nax.set_ylim(0, 1)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図9: ユーザー内の解答順序と正答率の推移（学習曲線）](01-eda_files/figure-html/fig-learning-curve-output-1.png){#fig-learning-curve width=950 height=470}\n:::\n:::\n\n\n序盤 (0-50問目) の正答率は **50% 前後**と低いが、100問を超えるあたりから **65-70%** に上昇し、その後は安定する。この上昇は2つの要因が混在している:\n\n1. **アダプティブ出題**: Santa アプリが学習者レベルに合った問題を提示するようになる\n2. **真の学習効果**: 繰り返し練習による知識獲得\n\nKT モデルはこの両方を分離し、「学習者の潜在的な知識状態」を推定することが目標となる。\n\n## 7. 追加分析 — アクティブ日数とセッション行動\n\n::: {#cell-fig-active-days .cell execution_count=14}\n``` {.python .cell-code}\nuser_days = (\n    df.with_columns(\n        (pl.col(\"timestamp\") // (86400 * 1000)).alias(\"day\")\n    )\n    .group_by(\"user_id\")\n    .agg(pl.col(\"day\").n_unique().alias(\"active_days\"))\n)\nad = user_days[\"active_days\"].to_numpy()\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\nax.hist(ad, bins=np.arange(0.5, min(ad.max(), 50) + 1.5, 1),\n        color=BLUE, edgecolor=\"white\", linewidth=0.4)\nax.set_xlabel(\"アクティブ日数\")\nax.set_ylabel(\"ユーザー数\")\nax.set_title(\"ユーザー別アクティブ日数の分布\", fontsize=13, fontweight=\"bold\")\nax.annotate(f\"中央値 = {int(np.median(ad))}日\\n平均 = {np.mean(ad):.1f}日\",\n            xy=(0.7, 0.8), xycoords=\"axes fraction\", fontsize=10,\n            bbox=dict(boxstyle=\"round,pad=0.3\", fc=\"lightyellow\", ec=\"gray\"))\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図10: ユーザー別アクティブ日数の分布](01-eda_files/figure-html/fig-active-days-output-1.png){#fig-active-days width=854 height=421}\n:::\n:::\n\n\nアクティブ日数の中央値はわずか **1 日** — 大半のユーザーは1日だけ試して離脱している。平均 4.2 日との乖離は、少数のヘビーユーザーによる引き上げである。これはセクション 3 のエンゲージメント分析と整合する。\n\n## 8. まとめ — EDA から導く前処理方針\n\n### 発見事項の総括\n\n::: {#cell-fig-summary .cell execution_count=15}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 2, figsize=(14, 10))\n\n# (a) Engagement: log hist of seq_lens\nax = axes[0, 0]\nax.hist(n_arr, bins=np.logspace(0, np.log10(n_arr.max()), 40),\n        color=BLUE, edgecolor=\"white\", linewidth=0.3)\nax.set_xscale(\"log\")\nax.set_xlabel(\"系列長\")\nax.set_ylabel(\"ユーザー数\")\nax.set_title(\"(a) エンゲージメント: 系列長\", fontweight=\"bold\")\nax.axvline(11, color=\"tomato\", ls=\"--\", lw=1.2, label=\"中央値 = 11\")\nax.legend(fontsize=8)\n\n# (b) Part accuracy\nax = axes[0, 1]\npart_colors = plt.cm.Set2(np.linspace(0, 1, 7))\nax.barh(labels_p[::-1], accs_p[::-1], color=part_colors[::-1], height=0.6)\nax.set_xlim(0.4, 0.85)\nax.xaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.set_title(\"(b) Part 別正答率\", fontweight=\"bold\")\n\n# (c) Elapsed time\nax = axes[1, 0]\ne_all = elapsed_sec.filter(pl.col(\"elapsed_sec\") <= 120)[\"elapsed_sec\"].to_numpy()\nax.hist(e_all, bins=60, color=GREEN, edgecolor=\"white\", linewidth=0.3, density=True)\nax.axvline(22, color=\"tomato\", ls=\"--\", lw=1.2, label=\"中央値 ≈ 22秒\")\nax.set_xlabel(\"解答時間 (秒)\")\nax.set_title(\"(c) 解答時間の分布\", fontweight=\"bold\")\nax.legend(fontsize=8)\n\n# (d) Learning curve\nax = axes[1, 1]\nax.scatter(rb, ra, s=np.clip(rn / 20, 5, 60), color=BLUE, alpha=0.3, edgecolors=\"none\")\nif len(ra) > window:\n    ax.plot(rb[window // 2: window // 2 + len(ma)], ma,\n            color=ORANGE, lw=2, label=\"移動平均\")\nax.set_xlabel(\"解答順位\")\nax.set_ylabel(\"正答率\")\nax.yaxis.set_major_formatter(ticker.PercentFormatter(1.0))\nax.set_title(\"(d) 学習曲線\", fontweight=\"bold\")\nax.legend(fontsize=8)\n\nfig.suptitle(\"EdNet-KT1 EDA サマリー\", fontsize=15, fontweight=\"bold\", y=1.01)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![図11: EDA サマリーダッシュボード](01-eda_files/figure-html/fig-summary-output-1.png){#fig-summary width=1334 height=973}\n:::\n:::\n\n\n### KT モデル向け前処理ポリシー\n\n| # | 方針 | 根拠 |\n|---|------|------|\n| 1 | **系列長 ≥ 10 のユーザーのみ使用** | Casual ユーザー (≤10問) は学習系列として短すぎ、KT モデルの学習・評価に不適切 |\n| 2 | **elapsed_time: 1秒未満 → 除外, 5分超 → 300秒にクリッピング** | 外れ値がノイズになるため。全体の 0.6% に影響 |\n| 3 | **correct 欠損行 (108件) → 除外** | 全体の 0.02% で無視可能 |\n| 4 | **concept = `tags` (multi-skill)** | 188 タグ、1問平均 2.4 タグ。question_id のみだとスパースすぎる |\n| 5 | **train/valid/test = ユーザー単位** で分割 (7:1.5:1.5) | 系列単位分割は情報リークのリスクがある |\n| 6 | **系列長キャップ = 2,000** | 上位 1% をトリミングし、GPU メモリの効率化を図る |\n\n::: {.callout-tip}\n## Next Step\n次のノートブック `02-baseline.qmd` では、ここで定めたポリシーに基づき前処理を実行し、IRT / BKT ベースラインの正答率予測精度を計測する。\n:::\n\n",
    "supporting": [
      "01-eda_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}